# -*- coding: utf-8 -*-
"""Aula06/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuUu9YHDZSijLqJWmJoO-s08_FEqhMNK

# **Aula 1**

## Atividade 1 - Operadores aritméticos
"""

x = 6 + 4 * 2
print(x)

x = (4 * 9 + 5)
print(x)

x = ((6 + 7) * 9)
print(x)

x = (15 + 20 - 30)
print(x)

x = (6 + 5**2)
print(x)

"""## Atividade 2 - Operadores de atribuição"""

x = 8
x += 5
x -= 4
x *= 20
x /= 2
print(x)

x = 8
x += 5
print(x)

x = 8
x -= 4
print(x)

x = 8
x *= 20
print(x)

x = 8
x /= 2
print(x)

"""## Atividade 3 - Operadores de comparação"""

x = 8
x1 = 3

x_result = x < x1
print(f'Resultado 1: {x_result}')
x_result = x == x1
print(f'Resultado 2: {x_result}')
x_result = x >= x1
print(f'Resultado 3: {x_result}')
x_result = x != x1
print(f'Resultado 4: {x_result}')

"""## Atividade 4 - Operadores lógicos e de identidade"""

x1 = 'botafogo'
x2 = 'flamengo'
x3 = 'botafogo'

x_result1 = x1 is x3
x_result2 = x1 is not x2
x_result3 = x1 is x2
x_result4 = x2 is x3

print(f'Resultado 1: {x_result1}')
print(f'Resultado 2: {x_result2}')
print(f'Resultado 3: {x_result3}')
print(f'Resultado 4: {x_result4}')

"""## Atividade 5 - Operadores de assosiação"""

frutas = ['banana','laranja','uva','ameixa']

x1 = 'banana'
x2 = 'laranja'
x3 = 'abacaxi'

x_result1 = x1 in frutas
x_result2 = x1 not in frutas
x_result3 = x2 not in frutas
x_result4 = x3 in frutas

print(f'Resultado 1: {x_result1}')
print(f'Resultado 2: {x_result2}')
print(f'Resultado 3: {x_result3}')
print(f'Resultado 4: {x_result4}')