# -*- coding: utf-8 -*-
"""Aula08/02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10J9CiKARLDxrnSATPKJ9FBLnKjEEOeh_

# **Aula 3 - Lista de exercícios**

## Atividade 1

Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

n1 = float(input('Digite primeiro número: '))
n2 = float(input('Digite segundo número: '))

soma = n1 + n2

if soma > 15:
  print(f'O resultado é maior que 15. Resultado: {soma}')

"""## Atividade 2

Faça um programa que recebendo um valor inteiro, informe se o número é positivo,
negativo ou neutro.
"""

n = int(input('Digite um valor inteiro: '))

if n > 0:
  print('O número é positivo!')
elif n < 0:
  print('O número é negativo!')
else:
  print('O número é nulo!')

"""## Atividade 3

Leia a idade e informe se a pessoa é maior ou menor de idade
"""

idade = int(input('Digite uma idade: '))

if idade >= 18:
  print('A pessoa é maior de idade')
else:
  print('A pessoa é menor de idade')

"""## Atividade 4

Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.
"""

temp = float(input('Informe uma temperatura: '))

if temp < 20:
  situacao = 'frio'
elif temp > 25:
  situacao = 'quente'
else:
  situacao = 'agradável'

print(f'A temperatura está {situacao}!')

"""## Atividade 5

Faça um programa em linguagem Python que leia dois números inteiros e informe
se estes são iguais ou diferentes.
"""

condicao = 'diferentes'

n1 = float(input('Digite primeiro número: '))
n2 = float(input('Digite segundo número: '))

verificacao = n1 == n2

if verificacao:
  condicao = 'iguais'

print(f'Os números são {condicao}!')

"""## Atividade 6

Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:

-  ACESSO PERMITIDO caso a senha seja válida.
-  ACESSO NEGADO caso a senha seja inválida.
"""

senha_valida = '1234'
acesso = 'NEGADO'

senha = input('Digite a senha: ')

if senha == senha_valida:
  acesso = 'PERMITIDO'

print(f'ACESSO {acesso}!')

"""## Atividade 7

Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou
igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas
menor do que 7, informar que o aluno está de exame; se a média for menor do que
5 informar que o aluno foi reprovado.
"""

n1 = float(input('Digite primeira nota: '))
n2 = float(input('Digite segunda nota: '))

media = (n1 + n2) / 2

if media >= 7:
  situacao = 'Aprovado'
elif media >= 5 and media < 7:
  situacao = 'de Exame'
else:
  situacao = 'Reprovado'

print(f'O aluno está {situacao}')

"""## Atividade 8

Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os
gols de cada time) e informe se o resultado foi um empate, se a vitória foi do
primeiro time ou do segundo time.
"""

gols_equipe1 = int(input('Digite o placar do time 1: '))
gols_equipe2 = int(input('Digite o placar do time 2: '))

if gols_equipe1 > gols_equipe2:
  resultado = 'Vitória da equipe 1'
elif gols_equipe1 < gols_equipe2:
  resultado = 'Vitória da equipe 2'
else:
  resultado = 'Empate'

print(f'O resultado do jogo foi: {resultado}!')

"""## Atividade 9

Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

opcoes = ['M','V','N']

print('Olá! em que período você estuda?')
print('M - matutino\nV - Vespertino\nN - Noturno')
periodo = input('Selecione o período: ').upper()

if periodo in opcoes:
  if periodo == opcoes[0]:
    mensagem = 'Bom Dia'
  elif periodo == opcoes[1]:
    mensagem = 'Boa Tarde'
  else:
    mensagem = 'Boa Noite'
else:
  mensagem = 'Valor Inválido'

print(f'{mensagem}!')

"""## Atividade 10

Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
-  Criança para 0 até 11 anos;
-  Adolescente para 12 até 18 anos;  
-  Jovem para 19 até 24 anos;  
-  Adulto para 25 até 40 anos;
-  Meia Idade para 41 até 60 anos;  
-   Idoso acima de 60 anos.
"""

idade = int(input('Digite uma idade: '))

if idade >= 0:
  if idade >= 0 and idade <= 11:
    classificao_etaria = 'Criança'
  elif idade >= 12 and idade <= 18:
    classificao_etaria = 'Adolescente'
  elif idade >= 19 and idade <= 24:
    classificao_etaria = 'Jovem'
  elif idade >= 25 and idade <= 40:
    classificao_etaria = 'Adulto'
  elif idade >= 41 and idade <= 60:
    classificao_etaria = 'Meia Idade'
  else:
    classificao_etaria = 'Idoso'
else:
    classificao_etaria = 'Inválida!'

print(f'Faixa etária: {classificao_etaria}')

"""## Atividade 11

As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
- salários até R$ 280,00 (incluindo) : aumento de 20%
- salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
- salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
- salários de R$ 1500,00 em diante : aumento de 5%
Após o aumento ser realizado, informe na tela:
- o salário antes do reajuste;
- o percentual de aumento aplicado;
- o valor do aumento;
- o novo salário, após o aumento.
"""

salario = float(input('Insira seu salário: '))

if salario > 0:
  if salario <= 280:
    percentual = 0.2
  elif salario > 280 and salario <= 700:
    percentual = 0.15
  elif salario > 700 and salario < 1500:
    percentual = 0.1
  else:
    percentual = 0.05
else:
  percentual = 0

valor_aumentado = salario*percentual
novo_salario = salario + valor_aumentado

print(f'Salário antes do reajuste: R${salario}\nPercentual aumentado aplicado: {percentual*100}%\nValor aumentado: R${valor_aumentado}\nNovo salário: R${novo_salario}')

"""## Atividade 12

Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.
"""

numero = float(input('Digite um número correspondente a semana. Ex: 1- Domingo 2- Segunda... : '))

if numero == 1:
  dia = 'Domingo'
elif numero == 2:
  dia = 'Segunda'
elif numero == 3:
  dia = 'Terça'
elif numero == 4:
  dia = 'Quarta'
elif numero == 5:
  dia = 'Quinta'
elif numero == 6:
  dia = 'Sexta'
elif numero == 7:
  dia = 'Sabádo'
else:
  dia = 'Valor inválido.'

print(dia)

"""## Atividade 13

Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de
Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta
do usuário, faça a devida conversão.
"""

opcoes = ['1','2']
print('Selecione sua conversão: 1 - Celsius/Fahrenheit\n2 - Fahrenheit/Celsius')

opcao = input('Sua opção: ')

if opcao in opcoes:
  if opcao == opcoes[0]:
    tipo = 'F°'
    temp = float(input('Insira sua temperatura C°: '))
    conversao = (temp*1.8) + 32
  else:
    tipo = 'C°'
    temp = float(input('Insira sua temperatura F°: '))
    conversao = (temp - 32) / 1.8
  print(f'Resultado da conversão: {conversao} {tipo}')
else:
  print('A opção seleciona é inválida!')

"""## Atividade 14

Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
- Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
- Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
- Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
- Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).
"""

idade = int(input('Digite uma idade: '))

if idade < 16:
  condicao = 'Proibido'
elif idade >= 16 and idade < 18:
  condicao = 'Optativo'
elif idade >= 18 and idade < 65:
  condicao = 'Obrigatório'
else:
  condicao = 'Optativo'

print(f'Condição de votar: {condicao}')

"""## Atividade 15

Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
- “Telefonou para a vítima? “
- “Esteve no local do crime?”
- “Mora perto da vítima? “
- “Devia para a vítima? “
- “Já trabalhou com a vítima? “

O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
Caso contrário, ele será classificado como “Inocente“.
"""

opcoes = ['S', 'N']
perguntas = ['Telefonou para a vítima?','Esteve no local do crime?','Mora perto da vítima?','Devia para a vítima?','Já trabalhou com a vítima?']
contador = 0

print('Responda as perguntas com "S/s" para Sim ou "N/n" para Não:\n')
for pergunta in perguntas:
  resposta = input(f'{pergunta}\nResposta: ').upper()
  while resposta not in opcoes:
    resposta = input(f'Opção inválida, responda novamente\n{pergunta}\nResposta: ').upper()
  if resposta == opcoes[0]:
    contador += 1

if contador == 2:
  classificacao = 'Suspeita'
elif contador >= 3 and contador < 5:
  classificacao = 'Cúmplice'
elif contador == 5:
  classificacao = 'Assassino'
else:
  classificacao = 'Inocente'

print(f'Classificação do participante: {classificacao}!')

"""## Atividade 16

Faça um programa que pergunte o preço de três produtos e informe qual produto
você deve comprar, sabendo que a decisão é sempre pelo mais barato.
"""

produtos = []
iguais = 0

for i in range(1,4):
  produto = float(input(f'Digite o preço do produto {i}: R$ '))
  produtos.append(produto)

menor_valor = min(produtos)

for produto in produtos:
  if produto == menor_valor:
    iguais += 1

if iguais == 1:
  print(f'Você pode comprar o produto de valor R$ {menor_valor}')
else:
  print(f'Você pode comprar {iguais} produtos de mesmo valor, sendo eles de R$ {menor_valor}')